---
# A workflow to test all the components have one or more of examples.
name: Check components and examples
on:
  pull_request:
    types:
      - labeled
      - synchronize

jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.result }}
    steps:
      - id: skip_check
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            console.log("context");
            console.log(JSON.stringify(context, null, 2));
            let should_skip = false;

            switch(context.payload.action) {
              case "labeled":
                if (context.payload.label.name != "area:components") {
                  should_skip = true;
                }
                if (context.payload.label.name == "area:ci") {
                  should_skip = false;
                }
                break;
              case "synchronize":
                let labels = context.payload.pull_request.labels.map(label => { return label.name });
                if (!labels.includes("area:components")) {
                  should_skip = true;
                }
                if (labels.includes("area:ci")) {
                  should_skip = false;
                }
                break;
              }
            return should_skip;

  check_components_and_examples:
    runs-on: ubuntu-latest
    needs: pre_build
    if: ${{ needs.pre_build.outputs.should_skip != 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check components and examples
        run: |
          all_components=`ls -1 components`
          exit_status=0

          for component in ${all_components}; do
            echo "Checking component \"${component}\""
            echo -n "it has examples/${component} directory: "
            if [ -d "examples/${component}" ]; then
              echo "yes"
            else
              echo "no"
              echo "the example directory for ${component} does not exist. create examples/${component} directory, and create an example for ${component} under examples/${component}/default."
              exit_status=1
            fi
            echo -n "it has the default example directory: "

            # allow both directory and symlink
            if [ -d "examples/${component}/default" ] || [ -L "examples/${component}/default" ]; then
              echo "yes"
            else
              echo "no"
              echo "the default example directory for ${component} does not exist. create examples/${component}/default directory, and create an example in that directory"
              exit_status=1
            fi
          done
          if [ $exit_status -eq 1 ]; then
            echo "Some tests failed. See the above log for details"
          fi
          exit ${exit_status}
