name: Metadata
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        working-directory: devtools
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake
    - run: |
        # Test if README.md is up-to-date with the metadata. If thies test
        # fails, update README.md by:
        #
        # bundle exec rake readme > README.md
        cd devtools && bundle exec rake readme > ../README.md
        git diff --exit-code README.md
